apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: cryptoengine-prometheus
    url: http://prometheus:9090
    access: proxy
    isDefault: false
    editable: false
    jsonData:
      httpMethod: POST
      timeInterval: 15s
